Switch to CMake and flatten relative include paths.
H-uru/imaginaryMyst pull request #1
Opened 2018-04-06 18:53 UTC by zrax

This should make reviving and actually working on imaginaryMyst easier.
TODO: Untangle circular dependencies...

2018-04-06 19:03 UTC, Deledrius commented
No circular dependency issues in my conversion: 8772ca9fa07a183808c5308b54f6b07b0d2befca
(https://github.com/H-uru/imaginaryMyst/compare/cmake)

2018-04-06 19:55 UTC, zrax commented
Sorry, I didn't realize you were working on the same thing...  :(

Questions though:  Why did you remove libsquish?  It's not provided by any Linux distros I'm aware of, and we still keep it in-source for libhsplasma...  Also, your version still doesn't fix the circular dependencies (look at the header files for those modules), it just doesn't mark them explicitly.  I had it without dependencies at first, but ran into link errors on Linux until I added them, which is when I noticed the circular dependency.

2018-04-06 20:16 UTC, Deledrius commented
MSVC strikes again!  It seems to handle the circular dependencies without complaint. >_<  Silly me for assuming they were gone.

I removed libSquish since it appeared you hadn't made any repo-specific changes requiring it to be in-tree.  I also have a version that keeps it, if desired.  I'm not working in Linux right now, so I wasn't aware of the (lack of) ease of installation there; I simply built my own and installed it system-wide.

2018-04-07 07:53 UTC, Deledrius requested changes

2018-04-07 07:53 UTC, Deledrius commented on src/CMakeLists.txt
> +add_executable(imaginaryMyst ${imCommon_HEADERS} ${imCommon_SOURCES})
We need `WIN32` here to link properly on Windows.

2018-04-08 22:26 UTC, Deledrius approved these changes

2018-04-09 03:08 UTC, merged